`include "rtl/picorv32/picorv32.v"
`include "rtl/picorv32/picorv32_pcpi_mul.v"
`include "rtl/picorv32/picorv32_pcpi_fastmul.v"
`include "rtl/picorv32/picorv32_pcpi_div.v"
`include "rtl/picorv32/picorv32_pcpi_bitrev.v"
`include "rtl/picorv32/picorv32_pcpi_gcd.v"
`include "rtl/picorv32/picorv32_pcpi_fft.v"
`include "rtl/picorv32/picorv32_axi.v"
`include "rtl/picorv32/picorv32_axi_adapter.v"

`include "rtl/axi4_lite_interconnect_m1s3.v"
`include "rtl/axi4_lite_slave.v"

// `include "rtl/picorv32_soc.v"
`include "rtl/axi_rom.v"
`include "rtl/axi_ram.v"
`include "rtl/gpio/gpio.v"
`include "rtl/gpio/axi4_lite_gpio_wrapper.v"