#!/usr/bin/env python3
"""
Membuat sinyal uji SATU nada (bukan dua nada dijumlah), pada tiga frekuensi
berbeda, masing-masing jadi file header C sendiri.

Kenapa satu nada: dengan satu nada, kalau filter benar, outputnya akan
kelihatan jelas -- amplitudonya besar (lolos) atau amplitudonya kecil
(diredam). Tidak ada nada kedua yang bisa membingungkan pembacaan.

Tiga frekuensi yang dibuat, relatif terhadap cutoff 500 Hz:

  100 Hz   -- jauh DI BAWAH cutoff  -> HARUS lolos hampir 100%
  500 Hz   -- TEPAT DI cutoff       -> HARUS diredam sampai ~0,707x (-3 dB)
  2000 Hz  -- jauh DI ATAS cutoff   -> HARUS diredam habis, hampir 0

Run:  python3 gen_single_tone.py

Hasil: test_signal_100hz.h, test_signal_500hz.h, test_signal_2000hz.h
"""
import math

FS   = 8000     # sama dengan laju sampling filter -- JANGAN diubah sendirian
N    = 256      # jumlah sampel
AMP  = 12000    # amplitudo -- aman di bawah batas 32767

FREKUENSI = [100, 500, 2000]


def buat_header(freq, nama_file):
    vals = []
    for n in range(N):
        v = AMP * math.sin(2 * math.pi * freq * n / FS)
        vals.append(int(round(v)))

    lines = [
        "/* Auto-generated by gen_single_tone.py -- do not edit by hand. */",
        "#ifndef TEST_SIGNAL_H",
        "#define TEST_SIGNAL_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define SIG_FS   {FS}",
        f"#define SIG_LEN  {N}",
        f"#define SIG_F    {freq}    /* frekuensi nada tunggal, Hz */",
        "",
        f"/* satu nada {freq} Hz, amplitudo {AMP}, fs = {FS} Hz */",
        f"static const int16_t test_signal[SIG_LEN] = {{",
    ]
    for i in range(0, N, 8):
        lines.append("    " + " ".join(f"{v:6d}," for v in vals[i:i + 8]))
    lines.append("};")
    lines.append("")
    lines.append("#endif /* TEST_SIGNAL_H */")

    with open(nama_file, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"  {nama_file:<26} {freq:5d} Hz   puncak = {max(abs(v) for v in vals)}")


print(f"Membuat sinyal satu-nada, fs = {FS} Hz, {N} sampel, amplitudo {AMP}\n")
for freq in FREKUENSI:
    buat_header(freq, f"test_signal_{freq}hz.h")

print("\nCara pakai: di main.c, ganti baris")
print('    #include "test_signal.h"')
print("menjadi salah satu dari:")
for freq in FREKUENSI:
    print(f'    #include "test_signal_{freq}hz.h"')
print("\nlalu build ulang (make sim-dump) untuk melihat frekuensi itu lolos atau tidak.")