#!/usr/bin/env python3
"""
Generate the test signal that the C program pushes through the filter.

Two tones: one well inside the 500 Hz lowpass passband, one well inside the
stopband.  After filtering the second tone should be gone, which makes the
result obvious even by eye in a memory dump.

Run:  python3 gen_test_signal.py
"""
import math

FS      = 8000
N       = 256
F_PASS  = 300     # inside the passband of every lowpass preset
F_STOP  = 2500    # deep in the stopband
AMP     = 6000    # per tone, so the sum peaks near 12000 of 32767

vals = []
for n in range(N):
    v = (AMP * math.sin(2 * math.pi * F_PASS * n / FS)
       + AMP * math.sin(2 * math.pi * F_STOP * n / FS))
    vals.append(int(round(v)))

assert max(abs(v) for v in vals) < 32767

lines = [
    "/* Auto-generated by gen_test_signal.py -- do not edit by hand. */",
    "#ifndef TEST_SIGNAL_H",
    "#define TEST_SIGNAL_H",
    "",
    "#include <stdint.h>",
    "",
    f"#define SIG_FS      {FS}",
    f"#define SIG_LEN     {N}",
    f"#define SIG_F_PASS  {F_PASS}",
    f"#define SIG_F_STOP  {F_STOP}",
    "",
    f"/* {F_PASS} Hz + {F_STOP} Hz, {AMP} amplitude each, fs = {FS} Hz */",
    f"static const int16_t test_signal[SIG_LEN] = {{",
]
for i in range(0, N, 8):
    lines.append("    " + " ".join(f"{v:6d}," for v in vals[i:i + 8]))
lines.append("};")
lines.append("")
lines.append("#endif /* TEST_SIGNAL_H */")

with open("test_signal.h", "w") as f:
    f.write("\n".join(lines) + "\n")

print(f"wrote test_signal.h: {N} samples, peak {max(abs(v) for v in vals)}")
